name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC dev command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (CMake)
        run: cmake -B build -G "Visual Studio 18 2026" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release --verbose

      - name: Upload injector
        uses: actions/upload-artifact@v4
        with:
          name: mcinjector
          path: build/injector/Release/mcinjector.exe

      - name: Upload payload
        uses: actions/upload-artifact@v4
        with:
          name: mcpayload
          path: build/payload/Release/mcpayload.dll
