name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC dev command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Configure (CMake)
        run: cmake -B build -G "Visual Studio 18 2026" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcinjector
          path: |
            build/injector/Release/mcinjector.exe
            build/payload/Release/mcpayload.dll
